Initialized project. Added config, tailwind, locale. added version in…
glebshbv/testguru pull request #1
Opened 2024-07-22 09:13 UTC by glebshbv

List of changes: 

- Set Up Project Repository and Branches
- Updated the Rails application configuration to set the time zone to 'Singapore' and the default locale to English (:en).
- Added an initializer (`version.rb`) in config/initializers/ to set the application version 
- Created a static /about page, did basic frontend
- Created a static /about/author page, did basic frontend
- Updated the README.md file as per task

2024-07-22 13:57 UTC, VidgarVii requested changes

2024-07-22 13:57 UTC, VidgarVii commented on app/controllers/about_controller.rb
> +class AboutController < ApplicationController
`html` файлы целиком статические
их будет оптимальнее отдать вообще в обход рельсового приложения (так будет работать быстрее, да и рельсам с этими файлами делать то нечего)
для этого их достаточно поместить в директорию `public`

роуты при этом не нужны и контроллеры тоже
(путь к файлу внутри директории `public` должен соответствовать пути, по которому этот файл должен быть доступен)

2024-07-22 13:57 UTC, VidgarVii commented on config/initializers/version.rb
> +  VERSION = '0.0.1'
патчить еще не чего.
Сейчас можно указать минорную версию ПО

сразу про константы следующий момент:

"мутабельные" объекты (строки, хэши, массивы) рекомендуется `freeze`-ить, чтобы они были неизменяемыми
в противном случае константу, ссылающуюся на "мутабельный" объект,  можно изменить: `VERSION << '3.14..'`

2024-07-23 09:27 UTC, glebshbv commented on config/initializers/version.rb
> +  VERSION = '0.0.1'
Resolved

2024-07-23 09:37 UTC, glebshbv commented on config/initializers/version.rb
> +  VERSION = '0.0.1'
resolved

2024-07-23 09:37 UTC, glebshbv commented on app/controllers/about_controller.rb
> +class AboutController < ApplicationController
resolved

2024-07-23 17:24 UTC, VidgarVii commented on config/routes.rb
> +  get 'about', to: 'about#index'
эти маршруты не нужны

2024-07-25 02:38 UTC, glebshbv commented on config/routes.rb
> +  get 'about', to: 'about#index'
забыл убрать

2024-07-25 02:38 UTC, merged