Lesson10
glebshbv/testguru pull request #12
Opened 2024-09-28 09:16 UTC by glebshbv

Homework

2024-09-28 11:11 UTC, VidgarVii requested changes

2024-09-28 11:11 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +  def start
экшен `start` в контроллере админа не нужен
это функционал пользователя

2024-09-28 11:11 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +      flash[:notice] = "Hi, #{current_user.name}!"
этот метод должен просто возвращать путь
то что он еще и флеш устанавливает - неожиданный сайд эффект
к примеру, есть задача:
в админке выводить список пользователей с урлами, куда каждый будет редиректнут после логина
метод называется `after_sign_in_path_for(user)` - вполне логично им воспользоваться
и вдруг неожиданность - у админа почему-то выводится флеш-привествие )))
ТЗ: "... после входа, выводить флэш-сообщение ..."
обрати внимание - "после входа", т.е. установку флеша надо делать там, где происходит логин пользователя (создание сессии), т.е. в `SessionsController`

2024-09-28 11:11 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[ start]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2024-09-28 11:11 UTC, VidgarVii commented on db/migrate/20240928072326_add_type_to_users.rb
> +class AddTypeToUsers < ActiveRecord::Migration[7.1]
код этой миграции можно объеденить в миграцию выше

2024-09-29 13:47 UTC, glebshbv commented on app/controllers/application_controller.rb
> +      flash[:notice] = "Hi, #{current_user.name}!"
ааааа)))

2024-09-30 05:51 UTC, merged