added required models
glebshbv/testguru pull request #2
Opened 2024-07-27 03:24 UTC by glebshbv

Created Rails Models with Necessary Attributes:

- Test
- Question
- Answer
- User
- Category

Я не добавлял relations, тк в задаче не было. могу откатить миграции и настроить ORM

2024-07-27 14:17 UTC, VidgarVii requested changes

2024-07-27 14:17 UTC, VidgarVii commented on db/migrate/20240727030652_create_tests.rb
> +
на этом задании надо еще добавить связи м/у таблицами. 
Так как тест принадлежит определенной категории надо использовать метод references
пример

```
t.references :category, null: false, foreign_key: true
```

тут мы укажем, что поле должно быть обязательно заполнен и обеспечим ссылочную целостность данных, через внешний ключ
[внешние ключи](https://en.wikipedia.org/wiki/Foreign_key)


Тест принадлежит Категории и Автору
Вопрос принадлежит тесту 
Ответ принадлежит вопросу

Вспомни ДЗ про SQL там уже добавляли эти связи

2024-07-27 14:17 UTC, VidgarVii commented on db/migrate/20240727030652_create_tests.rb
> +      t.integer :level, default: 1
Всем обязательным полям стоит добавить null false

2024-07-27 14:17 UTC, VidgarVii commented on db/migrate/20240727031202_create_answers.rb
> +      t.boolean :correct, default: true
для логических полей рекомендуется запрещать `null`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2024-07-28 05:13 UTC, glebshbv commented on db/migrate/20240727030652_create_tests.rb
> +      t.integer :level, default: 1
а если есть дефолт, все равно надо null false? если мы создадим обьект с пустыми полями и запишем в бащу, он же создаст дефолТ? или есть исключение. как правильно делать? @VidgarVii

2024-07-29 07:16 UTC, VidgarVii requested changes

2024-07-29 07:16 UTC, VidgarVii commented on db/migrate/20240729043849_initial_migration.rb
> +end
класть всё в 1 миграцию точно не стоит. 
Создание 1 таблицы = 1 миграция

2024-07-30 08:47 UTC, merged