added seeds. added relation on user and tests. added instance and cla…
glebshbv/testguru pull request #3
Opened 2024-07-31 04:09 UTC by glebshbv

- Added seeds file
- Added active record relations between User and Test
- added user instance method
- added test class method on join table
- added Category active record relation

2024-07-31 06:38 UTC, VidgarVii requested changes

2024-07-31 06:38 UTC, VidgarVii commented on app/models/test.rb
> +    joins(:category)
с ассоциациями ты поторопился, это будет чуть дальше в курсе
можно наверное их оставить, если есть понимание как они работают, т.е. какие SQL запросы строятся с их помощью
но лучше убрать. В данном ПР у тебя почти везде ошибки
мы к ним вернемся скоро, но до этого разберемся как собственно связываются между собой таблицы и зачем нам эти самые ассоциации нужны

2024-07-31 06:38 UTC, VidgarVii commented on app/models/user.rb
> +    tests.where(level: level)
то же само.
Плюс метод не рабочий. Внимательно прочти задание и протестируй свой код

2024-07-31 15:29 UTC, VidgarVii requested changes

2024-07-31 15:29 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
https://github.com/glebshbv/testguru/pull/3#discussion_r1697977131

2024-07-31 15:29 UTC, VidgarVii commented on app/models/user.rb
> +  enum user_type: {
не пригодиться. И этого нет в ТЗ

2024-07-31 15:29 UTC, VidgarVii commented on app/models/user.rb
> +  has_and_belongs_to_many :taken_tests, class_name: 'Test', join_table: :attendance
https://github.com/glebshbv/testguru/pull/3#discussion_r1697977131
И ассоциация была выбрана не верна.

2024-07-31 15:29 UTC, VidgarVii commented on app/models/user.rb
> +  def tests_by_level(level)
не работает

2024-07-31 15:29 UTC, VidgarVii commented on db/migrate/20240731103050_create_join_table_user_test.rb
> +    create_join_table :users, :tests, table_name: :attendance do |t|
смотрим файл readme
У тебя сущность под номером 7 Результат. Вот его и надо вводить в проект.
И в таблице надо будет сделать связи с юзером и тестом. Если етсь запись в этой таблице, значит юзер прошел или проходит тест.

2024-08-02 05:03 UTC, glebshbv commented on db/migrate/20240731103050_create_join_table_user_test.rb
> +    create_join_table :users, :tests, table_name: :attendance do |t|
до меня дошло

2024-08-02 14:13 UTC, VidgarVii requested changes

2024-08-02 14:13 UTC, VidgarVii commented on db/migrate/20240802052418_create_results.rb
> +      t.references :answer, null: false, foreign_key: true
зачем тут ответ? Этого нет в ТЗ. Логику делать будет потом.
Пока достаточно добавть связьи м/у юзером и тестом

2024-08-02 14:13 UTC, VidgarVii commented on db/migrate/20240802052418_create_results.rb
> +      t.integer :result, default: 0, null: false
result.result 
Такая тавтология не приветствуется. 
И данное поле не нужно

2024-08-02 14:13 UTC, VidgarVii commented on db/migrate/20240729074151_create_users.rb
> +      t.integer :user_type, default: 10, null:false
этого нет в тз

2024-08-02 14:13 UTC, VidgarVii commented on app/models/user.rb
> +  end
Создайте инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и **возвращает список всех Тестов**, которые проходит или когда-либо проходил Пользователь на этом уровне сложности

2024-08-04 11:48 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins("INNER JOIN results ON results.test_id = tests.id INNER JOIN users on results.user_id = users.id")
тут достаточно объеденить только таблицу results.
А нужного юзера можно найти по полю user_id у таблицы results

2024-08-04 11:48 UTC, VidgarVii commented on app/models/user.rb
> +        .select("tests.*")
select тут не особо нужен. Метод вернёт объекты тестов

2024-08-04 13:50 UTC, merged