fixed forms. added helpers. added footer
glebshbv/testguru pull request #7
Opened 2024-08-20 07:23 UTC by glebshbv

2024-08-20 14:11 UTC, VidgarVii requested changes

2024-08-20 14:11 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    def index
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2024-08-20 14:11 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +      </footer>
мы за единообразие в коде.
Стоит во всём проекте использовать отступ в 2 пробела

2024-08-20 14:11 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +      <footer class="mt-auto w-full flex justify-center items-center">
тег footer можно определить внутри файла shared/footer
И тогда всё будет в одном месте

2024-08-20 14:11 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +  <%= form_with model:[@test, @question], local: true do |form| %>
уже ведь есть паршал form
Сейчас это просто дублирование кода. 
Тут лучше рендерить паршал для формы. И саму форму сделать так, чтобы она работала при создании и обновлении ресурса. Как это сделать указано в ТЗ

2024-08-20 14:11 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +</div>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-08-20 14:11 UTC, VidgarVii commented on app/views/shared/_footer.html.erb
> +    <%= link_to "Test Guru", 'https://github.com/your-username/your-repo', class: 'text-blue-600 hover:underline' %>
Для формирования ссылки на GitHub репозиторий: github_url(author, repo)

2024-08-20 14:11 UTC, VidgarVii commented on app/views/shared/_footer.html.erb
> +    <%= link_to "Test Guru", 'https://github.com/your-username/your-repo', class: 'text-blue-600 hover:underline' %>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2024-08-23 06:08 UTC, VidgarVii requested changes

2024-08-23 06:08 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> -  def show
страница show нужна.
по ТЗ только список вопросов показываем на странице теста.

Нам еще с ответами работать. Которых надо будет показывать на странице вопроса.

2024-08-23 06:08 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +end
все экшаны надо реализовать

2024-08-23 06:08 UTC, VidgarVii commented on app/helpers/question_helper.rb
> +  end
ТЗ: Напишите хэлперы Для формирования ссылки на GitHub репозиторий: github_url(author, repo)
Сейчас метод просто возвращает строку. А нужна хтмл ссылка. А то полезности от метода мало

2024-08-23 06:08 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +      <%= render 'shared/footer' %>
надо поправить отступ

2024-08-23 06:08 UTC, VidgarVii commented on app/views/questions/_form.html.erb
> +<%= form_with model: @question.new_record? ? [@test, @question] : @question, local: true, class: "p-6" do |form| %>
не нужно писать услоный блок
просто пишешь `form_with model: [@test, @question]`
для эдит переменная `@test` будет пустая (не надо ее в контроллере искать, т.к. при использовании опции "шеллоу тру" в роутах для эдит `@test` не нужен)
соответсвенно в `@test` будет "нил" и рельсы построят правильный путь, потому что придет только `@question`
для нью придут оба объекта ("тест" и "квесшен") и рельсы также построят правильный путь

2024-08-23 13:47 UTC, VidgarVii requested changes

2024-08-23 13:47 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to tests_path, notice: 'Question was successfully created.'
после создания/обновления ресурса принято показывать этот ресурс. Т.е. тут хорошо бы сделать редирект на страницу вопроса

2024-08-23 13:47 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test.author_id = "19"
а если нет такого юзера с ид 19?
При создании теста для указания автора лучше использовать методы ассоциации. Так же как создаётся вопрос.
А юзера можно взять первого. И не принимать author_id в test_params. Всё-ровно форма не передаёт author_id

2024-08-23 13:47 UTC, VidgarVii commented on app/views/tests/_form.html.erb
> +  <% end %>
вот этот кусок кода для ошибок валидаций стоит вынести отдельно в паршал. Так как он нужен для остальных ресурсов (вопросы/ответы)

2024-08-23 13:47 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +        <% test.questions.each_with_index do |question, index| %>
для рендера коллекций обычно используют render collection
http://rusrails.ru/layouts-and-rendering-in-rails#rendering-kollektsiy

```ruby
  render @questions
```

- Это разгрузит данный файл
- Наведет порядок. Вся работа с нужными ресурсами будет вестись в своей папке
- Позволит удобней кешировать куски страницы

в скринкасте про лэйауты и паршелы рассказывается про рекомендуемый вариант рендеринга коллекций (примерно после 20:30)

2024-08-23 13:47 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +        <% test.questions.each_with_index do |question, index| %>
по ТЗ вопросы надо показывать на странице конкретного теста, а не всех тестов

2024-08-23 13:49 UTC, glebshbv commented on app/controllers/tests_controller.rb
> +    @test.author_id = "19"
так костыль..... у нас нет же сессии с current_user

2024-08-25 11:08 UTC, VidgarVii requested changes

2024-08-25 11:08 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test.author = User.first
не использован метод ассоциации. Посмотри как создаётся вопрос

2024-08-25 11:08 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to tests_path, notice: 'Question was successfully updated.'
https://github.com/glebshbv/testguru/pull/7#discussion_r1728997999
не исправлено

2024-08-25 11:08 UTC, VidgarVii commented on app/views/shared/_error.html.erb
> +
no lew line ..
скроей всего затясался пробел

2024-08-25 11:08 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +  <% @tests.each do |test| %>
не исправлено
https://github.com/glebshbv/testguru/pull/7#discussion_r1729007724

2024-08-26 02:41 UTC, glebshbv commented on app/controllers/tests_controller.rb
> +    @test.author = User.first
ДОШЛО!!

2024-08-26 06:25 UTC, merged