Lesson8
glebshbv/testguru pull request #8
Opened 2024-09-05 11:56 UTC by glebshbv

2024-09-05 15:56 UTC, VidgarVii requested changes

2024-09-05 15:56 UTC, VidgarVii commented on app/controllers/results_controller.rb
> +  def show
`def show; end`

2024-09-05 15:56 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :set_user, only: %i[ start ]
для 1 экшена колбек не объявляют. Это делает код в экшенах не явными, что сильно усложняет код и отладку

2024-09-05 15:56 UTC, VidgarVii commented on app/models/result.rb
> +  end
в ТЗ указан код в 1 строчку. Правда его надо до работать

2024-09-05 15:56 UTC, VidgarVii commented on app/models/result.rb
> +  before_update :set_current_next_question
эти два коллбека делают одно и то же по сути
оба устанавливают следующий вопрос
разница лишь в том, что считать следующим вопросом, т.е разница в поиске этого следующего вопроса

(и обрати внимание - оба вызываются с дополнительным условием, на создании или на апдейте)

имеет смысл объединить их в один простой коллбек:

```ruby
before_validation :set_current_question

...

def set_current_question
  self.current_question = next_question
end
```
а всю различающуюся логику поместить уже в метод `next_question`

(коллбеки бывает удобно использовать, но они часто усложняют код и его отладку, если есть возможность не плодить лишние, то ей надо воспользоваться)


вообще с коллбеками нужно осторожно - они не всегда делают то что ты ожидаешь, тогда когда ты ожидаешь ))
бывают ньюансы о которых не догадываешься, особенно при совместной работе нескольких коллбеков и использовании коллбеков с условиями
поэтому если есть возможность упростить коллбеки, то это нужно делать

2024-09-05 15:56 UTC, VidgarVii commented on app/views/results/result.html.erb
> +    <% if success_percentage >= 85 %>
`success_percentage = (@test_passage.correct_questions.to_f / @test_passage.test.questions.count) * 100`
и
`if success_percentage >= 8` - это бизнес-логика
шаблоны (вьюхи) точно не должны ничего знать про бизнес логику вообще
место бизнес-логики в моделях

здесь можно использовать что-то такое:
```ruby
if @test_passage.success?
```

2024-09-06 15:44 UTC, merged

2024-09-07 05:09 UTC, VidgarVii commented on app/models/result.rb
> +  end
выражение calculate_percentage >= 0.85 и так будет возвращать true/false

2024-09-07 05:09 UTC, VidgarVii commented on app/models/result.rb
> +    correct_questions.to_f / total_questions_count.to_f
достаточно одного вызова to_f

2024-09-07 05:09 UTC, VidgarVii commented on app/models/result.rb
> +
тут явно какие-то методы должны быть приватными

2024-09-07 05:09 UTC, VidgarVii commented on app/models/result.rb
> +     correct_answers.ids.sort == answer_ids.map(&:to_i).sort
как я писал ранее, что метод надо доработать. answer_ids может не быть. Например когда юзер не выбрал ответ

2024-09-08 07:33 UTC, glebshbv commented on app/models/result.rb
> +
так они приваиные же

2024-09-08 18:46 UTC, VidgarVii commented on app/models/result.rb
> +  end
не исправлено